### ISSUE TITLE
Show de post: Puedo ir al anterior y al siguiente cronológico (sin importar el autor). También figura un link a los posts del autor

### ISSUE THREAD

**Issue by silvagustin** [silvagustin/xaver-blog-2#11]

**Comment by xavierperera** [comment]
Ferpecto

**Comment by xavierperera** [comment]
Anterior y Siguiente lo pasaria a metodos de instancia:
 @post.anterior
 @post.siguiente

 En vez de Post.anterior(un_post).

 Y para metodo de clase lo dejaria para que devuelva una relation:
 Post.anteriores(un_post)
 Post.siguientes(un_post)

 Y @post.anterior podria hacer uso de Post.anteriores(self).last, por ej.

 Distintas formas de resolver lo mismo...

**Comment by silvagustin** [comment]
Cambios realizados. Me queda una duda si esta bien esto, ya que al hacerlo de esta forma yo hago un **@post.siguiente** en la vista y este metodo hace una consulta con la BD que lo deberia hacer el Controller segun el modelo MVC. O deberia haber hecho 2 variables de clase en el Controller (**anterior** y **siguiente**), asignarles sus respectivos valores con los metodos de instancias definidos en Post y luego llamarlos desde la view?

**Comment by xavierperera** [comment]
Lo q decis es correcto y buena practica.

**Comment by silvagustin** [comment]
Okey, hice lo ultimo. Cierro issue.
