### ISSUE TITLE
I18n::InvalidLocale: :en is not a valid locale

### ISSUE THREAD

**Issue by xavierperera** [silvagustin/xaver-blog-2#17]
En algun lado se setea el uso del idioma :en, pero en application.rb solo haces disponible :en.

Para poder seedear tuve que agregar :en como idioma:
 config.i18n.available_locales = %i(es en)

**Comment by xavierperera** [comment]
Esto sigue fallando,
 Para ver el error: rake db:seed

**Comment by silvagustin** [comment]
Estuve leyendo un poco sobre Internationalization y despues de eso ordene los locales como [indica la guia](http://guides.rubyonrails.org/i18n.html#organization-of-locale-files). Luego, en **Application.rb**, coloque las siguientes 3 lineas:
`# Where the I18n library should search for translation files
I18n.load_path += Dir[Rails.root.join('lib', 'locale', '*.{rb,yml}')]
 
# Whitelist locales available for the application
I18n.available_locales = [:en, :pt]
 
# Set default locale to something other than :en
I18n.default_locale = :pt`

**Comment by xavierperera** [comment]
Te tira error porque si bien en tu app nunca requeris un idioma distinto al :es, hay en algun lado algun plugin/vendor que esta en locale :en. Si no lo pones entre los available_locales va a tirar error

**Comment by xavierperera** [comment]
%i(es en) es lo mismo que [:es, :en]
%w(es en) es lo mismo que ['es', 'en']

**Comment by silvagustin** [comment]
Ahh mira vos. Raro porque le puse todos los locales en espanol, salvo para **simple_form** que no encontre.

Si si, eso lo se. Me refiero a cuando quiero hacer lo siguiente: `config.i18n.available_locales = %i(es en)`, es lo mismo que hacer: `I18n.available_locales = %i(es en)`?

**Comment by xavierperera** [comment]
Mm.. por como esta hecho creo que ambas opciones llegan al mismo resultado.
 Por un lado estas accediendo a internationalization desde el config, y por otro estas accediendo directamente a la clase/singleton.

 Es posible que config.i18n en definitiva devuelva I18n. Pero es probable que no. Usalo como diga la documentacion, ya que si en el futuro cambia podes llegar a tener problemas (dudo que pase).

**Comment by silvagustin** [comment]
Bárbaro! Cierro issue.
