### ISSUE TITLE
Si no estoy logueado me rebota.

### ISSUE THREAD

**Issue by silvagustin** [silvagustin/xaver-blog-2#2]

**Comment by xavierperera** [comment]
Si y no. Vos en el blog 1 tenes mezclado en un mismo controller lo que hace un visitante con lo que hace un administrador, y lo controlas por permisos.
Aca seguimos controlando por permisos. pero son 2 modulos independientes lo Publico con lo Administrable.

Ahora cuando bloqueas el acceso de una persona no bloqueada, lo haces en toooodo el namespace Admin, no solo en los action de edicion y creacion

**Comment by silvagustin** [comment]
Se actualizo el **ability.rb** y en **application_controller.rb** se actualizo el **rescue_from**. A un usuario lo deriva a post_path y a un usuario a admin_path.

**Comment by xavierperera** [comment]
Excelente,
 Correcciones: En Public y Admin controller no necesitas definir el layout si usas la estructura correcta,
 En views/layouts, tenes que poner admin.html y public.html, dentro de una carpeta con el mismo nombre:
 views/layouts/admin/admin.html.erb
 views/layouts/admin/public.html.erb

El before_action :authenticate_usuario!,  deberia estar en Admin::AdminController, y Post::AdminController lo hereda. De esta manera cualquier nuevo controller que crees en Admin, automaticamente estara protegido.

En cuanto a la herencia de los layouts basados en base.html.erb, lo que suele convenir es que no hereden del mismo sino que usen partials compartidos, por ejemplo en este caso crearia el partial /layouts/_header.html.erb y haria que tanto public como admin lo usen. Por que se hace esto? Es muy probable que public y admin tengan requerimientos distintos de css, y js, entre otras cosas. Fijate por ejemplo la web de Xaver y admin.xaver, difieren mucho.

En rescue_from, en vez de derivarlo a posts_path, es mas comun mandarlo a public_root_path o root_path (deberia se lo mismo). Y en cuanto a admin_path, fijate que podes usar 'root's distintos para cada namespace, asi que en vez de crear el admin_path manualmente, podes usar el root_path de admin (luego de que lo declares)

**Comment by silvagustin** [comment]
**Primer**, **segundo** y **cuarto** parrafos hechos. Al haber hecho un **namespace** Admin, cuando hacia el **root** me agregaba el sufijo **root**: admin_root_path. Mi idea era que quedara como **admin_path**, pero cuando le ponia el **as: :admin** me terminaba quedando **admin_admin_path**. Hay alguna forma de corregir esto? Como no pude lo deje tanto a public como a admin como **nombre_root_path**.

Ahora me pongo con el tercero.

**Comment by xavierperera** [comment]
Joya Obyyyy

Si queres usar admin_path y public_path, tenes que declararlos fuera de los modulos y namespaces.

**Comment by silvagustin** [comment]
Con el **tercer** parrafo me quede un poco porque no lo entendia. El archivo **base.html.erb** solo cuenta con el **head** del archivo HTML y en el **body** hace un **yield**, no tengo nada cargado ahi. Dependiendo donde este parado se carga el **layout** correspondiente: **/layouts/admin/admin.html.erb** o **layouts/public/public.html.erb**. Dentro de cada uno de ellos se carga el **header** y **footer** correspondiente, y entre ellos se hace un **yield** de lo que se quiera mostrar. Hay que tocar algo?

Por las dudas dejo el [link que utilice para esto](https://mattbrictson.com/easier-nested-layouts-in-rails) en el issue #8.

**Comment by xavierperera** [comment]
Luego reviso y te digo. Puede q este ok lo hecho.
