### ISSUE TITLE
Si estoy logueado veo mis posts, puedo crear, modificar y eliminar.

### ISSUE THREAD

**Issue by silvagustin** [silvagustin/xaver-blog-2#3]

**Comment by silvagustin** [comment]
Varias de las cosas que irian aca se dijeron en #2.

**Comment by xavierperera** [comment]
Si no estoy logueado, en Public veo tooodos los posts.
Si estoy logueado, en Public veo tooodos los posts (no cambia nada que este loguado o no)

Si no estoy logueado, no puedo entrar a admin.
Si estoy logueado puedo entrar a admin, pero ahi adentro veo SOLO mis posts, los cuales puedo modificar, eliminar, o agregar nuevos

**Comment by silvagustin** [comment]
Cambios realizados.

**Comment by xavierperera** [comment]
De 10
