### ISSUE TITLE
Mostrar fecha con este formato: 01/05/2017 17hs.

### ISSUE THREAD

**Issue by silvagustin** [silvagustin/xaver-blog-2#5]

**Comment by silvagustin** [comment]
En primera instancia de realizo definiendo un metodo en el Helper de Post. Pero debido al link de i18n que me paso Xavi, esto fue cambiado por la gema i18n. Se cambio el **locale** predeterminado a uno en espanol llamado **es.yml**, donde alli se definio una forma de impresion personalizada llamada **custom**.

**Comment by xavierperera** [comment]
Sigo viendo el viejo formato en algunos lados: Posteado por test@test.com el 2017-05-23 06:37:26 UTC.

**Comment by silvagustin** [comment]
Problema corregido en **Public**. Creé un helper en **/helpers/public/posts** llamado **fecha_de_publicacion**. Ahora debería hacer lo mismo para **Admin** en **/helpers/admin/posts**, pero no sería redundante tener el mismo código 2 veces? Se me ocurre hacer un directorio **/helpers/shared**, en donde hay un partial de **posts** y luego hacer el  yield tanto en **/public/posts** como en  **/admin/posts**.

**Comment by xavierperera** [comment]
Los helpers se comparten siempre asi q podes hasta meterlo en el
application_helper

**Comment by silvagustin** [comment]
Metodo **fecha_de_publicacion(post)** agregado al **application_helper**. Cierro issue.
