### ISSUE TITLE
La ruta por el namespace

### ISSUE THREAD

**Issue by silvagustin** [silvagustin/xaver-blog-2#8]
La ruta por el namespace Public debe ser el default:
localhost:3000/admin/
localhost:3000/admin/posts/
localhost:3000/admin/posts/1/edit

**Comment by silvagustin** [comment]
Intentando encontrarle una solucion a esto con los siguientes links:

- [Guides.rubyonrails](http://guides.rubyonrails.org/routing.html#overriding-the-named-helpers)

- [Teamtreehouse](http://blog.teamtreehouse.com/creating-vanity-urls-in-rails)

**Comment by silvagustin** [comment]
Estoy teniendo problemas con esto:
- Algunas de las rutas funcionan bien.
- Al hacer un nested routing con :usuarios (admin) y :posts, dejaron de funcionar el :create, :update y :destroy. Creo que tiene algo que ver con el encabezado de simple_form: `<%= simple_form_for @post do |f| %>`

Hay algunas cosas que se dejaron comentadas que me gustaria que las vieras. El branch es **configurar_rutas_admin**:
`$ git checkout configurar_rutas_admin`

**Comment by xavierperera** [comment]
La ruta por el namespace **ADMIN** debe ser:
localhost:3000/admin/
localhost:3000/admin/posts/
localhost:3000/admin/posts/1/edit

**Comment by xavierperera** [comment]
Ups mepa que el copy paste me jugo una mala pasada. La idea es que en routes uses namespaces para ADMIN y modules para PUBLIC (2.6 Controller Namespaces and Routing).

Como resultado en los controllers tendras 2 carpetas:
public
 -> public_controller.rb Public::PublicController < ApplicationController
 -> posts_controller.rb Posts::PublicController < Public::PublicController
admin
 -> admin_controller.rb Admin::AdminController < ApplicationController
 -> posts_controller.rb Posts::PostsController < Admin::AdminController

En los controllers de Public no vas a tener edits, updates ni destroys
En los controllers de Admin es donde haces el abm.

En cuanto a las vistas sucedera lo mismo, ahora vas a tener dos carpetas (Public y Admin), y dentro de esas carpetas tendras una carpeta posts
public
 -> posts
 -> -> index.html
 -> -> show.html
 -> -> etc
admin
 -> posts
 -> -> index.html
 -> -> show.html
 -> -> edit.html
 -> -> new.html
 -> -> etc

Public y Admin tendran tambien su propio Layout

**Comment by silvagustin** [comment]
Se hicieron los cambios pertinentes, antes no habia entendido del todo bien lo que habia que hacer. Links de ayuda:
- [Easier Nested Layouts in Rails](https://mattbrictson.com/easier-nested-layouts-in-rails)
- [Un layout por controller](https://rubyplus.com/articles/3071-Layouts-in-Rails-5)
- [DEVISE, Change the default sign_in and sign_out routes](https://github.com/plataformatec/devise/wiki/How-To:-Change-the-default-sign_in-and-sign_out-routes)
- [DEVISE, Redirect to a specific page on successful sign in
](https://github.com/plataformatec/devise/wiki/how-to:-redirect-to-a-specific-page-on-successful-sign-in)
- [SIMPLE_FOR, cuando la ruta esta anidada a un namespace](https://stackoverflow.com/questions/22666582/routing-error-no-route-matches-post-comments-new-using-scope)
- [Yield & Provide](http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-provide)

**Comment by xavierperera** [comment]
joyiiii
